main: ch.swisssmp.utils.EventPoints
version: 2
api-version: 1.13
name: EventPoints
author: detig_iii
description: Verwaltet Eventpunkte
depend: [WebCore,CustomItems]
permissions: 
  eventpoints.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
  smp.commands.balance:
    description: Erlaubt Verwendung des Befehls /balance
    default: true
commands:
  eventpoints:
    usage: |
      /eventpoints give [Spieler] [Menge] [Typ] [Grund]
      /eventpoints take [Spieler] [Menge] [Typ] [Grund]
      /eventpoints reload
    description: Verwaltet Eventpunkte
    aliases: [ep,eventpoint]
    permission: eventpoints.admin
  balance:
    description: Zeigt dein Vermögen an
    usage: /balance (Währung)
    permission: smp.commands.balance
    aliases: [eventpunkte]