main: ch.swisssmp.npc.NPCs
version: 3
api-version: 1.13
name: NPCs
author: detig_iii
description: Ermöglicht anderen Plugins Verwendung von NPCs
depend: [CustomItems,SwissSMPUtils,WebCore,CustomEditorAPI]
permissions:
  npc.admin:
    description: Erlaubt Verwaltung von NPCs
    default: op
commands:
  npc:
    description: Hauptbefehl zur Verwaltung von NPCs
    usage: "/<command> <subcommand> [Argumente]"
    permission: npc.admin
  npc create:
    description: Erstellt einen NPC an deiner Position
    usage: "/<command> <subcommand> [Typ]"
    permission: npc.admin
  npc pack:
    description: Verpackt alle NPCs in Spawn-Eier, ausführen bevor eine Welt umbenannt oder transferiert wird
    usage: "/<command> <subcommand>"
    permission: npc.admin
  npc unpack:
    description: Entpackt alle NPCs, ausführen nachdem eine Welt umbenannt oder transferiert worden ist
    usage: "/<command> <subcommand>"
    permission: npc.admin