package ch.swisssmp.craftmmo.mmoevent;

public enum MmoEventType {
DUNGEON_START,
REGION_ENTER,
REGION_LEAVE,
CAMP_TRIGGERED,
CAMP_CLEARED,
TRANSFORMATION_TRIGGERED,
QUEST_START,
QUEST_CLEARED,
QUEST_FAILED
;
}
