main: ch.swisssmp.adventuredungeons.AdventureDungeonsPlugin
version: 4.2
api-version: 1.13
name: AdventureDungeons
author: detig_iii
description: Dungeons in Minecraft ohne Mods
depend: [WorldGuard,WebCore,AreaTransformations,WorldGuardManager]
softdepend: [DungeonGenerator]
load: startup
permissions: 
  dungeons.admin:
    default: op
    description: Erlaubt die Verwaltung von AdventureDungeons
commands:
  dungeon:
    description: Verwaltet MmoDungeons
    usage: |
      /dungeon join [Dungeon-ID] [Schwierigkeit] (Spieler)
      /dungeon leave
      /dungeon edit [Dungeon-ID]
      /dungeon endedit
      /dungeon respawn_position [X] [Y] [Z] [Yaw] [Pitch]
      /dungeon play_sound [Instanz-ID] [Sound-ID]
    aliases: [mmodungeon]
    permission: dungeons.admin
  dungeons:
    description: Zeigt alle Dungeons an
    usage: /dungeons
    permission: dungeons.admin
  join:
    description: Betrete eine Dungeon Instanz eines anderen Spielers
    usage: /join [Spieler]
  leave:
    description: Verlasse eine Dungeon Instanz
    usage: /leave
    aliases: [quit,exit,verlassen]
  refuse:
    description: Lehne eine Anfrage eines Spielers ab
    usage: /refuse [Spieler]
  invite:
    description: Lade einen Spieler in deine Dungeon Instanz ein
    usage: /invite [Spielername]
    aliases: [inv]
  ready:
    description: Setze deinen Bereitschaftsstatus in einer Dungeon Instanz
    usage: /ready