main: ch.swisssmp.observatorium.ObservatoriumPlugin
version: '1.9'
api-version: '1.13'
name: Observatorium
author: WhiteGuggi
depend: [SwissSMPUtils,WorldGuard,WorldEdit,CitySystem,WebCore]
permissions:
  observatory.use:
    description: Erlaubt Nutzen des Observatoriums
    default: op
