main: ch.swisssmp.knightstournament.KnightsTournamentPlugin
version: 5
api-version: 1.13
name: KnightsTournament
authors: [detig_iii, WhiteGuggi]
description: Ritterspiele
depend: [SwissSMPUtils,WebCore,CustomItems,WorldManager,CustomEditorAPI,ResourcepackManager,ProtocolLib,WGRegionEvents,WorldGuard]
permissions: 
  knightstournament.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
  knightstournament.host:
    default: op
    description: Erlaubt die Leitung von Turnieren
  knightstournament.lance.craft:
    default: op
    description: Erlaubt das Craften von Turnierlanzen
  knightstournament.lance.charge:
    default: op
    description: Erlaubt Nutzen der Ritterlanze ausserhalb von Turnieren
  knightstournament.participate:
    default: op
    description: Erlaubt die Teilnahme an Ritterspielen
commands:
  knightstournament:
    usage: |
      /knightstournament start [Arena]
      /knightstournament end
    description: Steuert ein Turnier
    permission: knightstournament.admin
    aliases: [ritterspiel]
  knightsarena:
    usage: "/<command> <subcommand>"
    description: Hauptbefehl zur Verwaltung von Arenen
    permission: knightstournament.admin
    aliases: [ritterarena]
  knightsarena create:
    usage: "/<command> <subcommand>"
    description: Erstellt eine Arena
    permission: knightstournament.admin
  knightsarenas:
    usage: "/<command>"
    description: Zeigt erstellte Arenen
    permission: knightstournament.admin