main: ch.swisssmp.farm.CropFarmerPlugin
version: 1
api-version: 1.13
author: detig_iii
name: CropFarmer
description: Plantage-Addon, erlaubt effizienteres Bewirtschaften von Ackerland.
permissions:
  cropfarm.use:
    description: Erlaubt die Verwendung der Farm
    default: op