package ch.swisssmp.text;

import com.google.gson.JsonObject;
import net.md_5.bungee.api.chat.BaseComponent;

public class ClickEvent {

    public static final String OPEN_URL = "open_url";
    public static final String OPEN_FILE = "open_file";
    public static final String RUN_COMMAND = "run_command";
    public static final String SUGGEST_COMMAND = "suggest_command";
    public static final String CHANGE_PAGE = "change_page";
    public static final String COPY_TO_CLIPBOARD = "copy_to_clipboard";

    private String action;
    private String value;

    private ClickEvent(String action, String value){
        this.action = action;
        this.value = value;
    }

    public ClickEvent action(String action){
        this.action = action;
        return this;
    }

    public String action(){
        return action;
    }

    public ClickEvent value(String value){
        this.value = value;
        return this;
    }

    public String value(){
        return value;
    }

    public net.md_5.bungee.api.chat.ClickEvent spigot(){
        return new net.md_5.bungee.api.chat.ClickEvent(net.md_5.bungee.api.chat.ClickEvent.Action.valueOf(action.toUpperCase()), value);
    }

    public void apply(JsonObject json){
        JsonObject clickSection = new JsonObject();
        if(action!=null) clickSection.addProperty("action", action);
        if(value!=null) clickSection.addProperty("value", value);
        json.add("clickEvent", clickSection);
    }

    /**
     * Opens value as a URL in the user's default web browser.
     */
    public static ClickEvent openUrl(String value){
        return new ClickEvent(OPEN_URL, value);
    }

    /**
     * Opens the file at  value on the user's computer. This is used in messages automatically generated by the game
     * (e.g., on taking a screenshot) and cannot be used by players for security reasons.
     */
    public static ClickEvent openFile(String value){
        return new ClickEvent(OPEN_FILE, value);
    }

    /**
     * Works in signs, but only on the root text component, not on any children. Activated by using the sign. In chat
     * and written books, this has value entered in chat as though the player typed it themselves and pressed enter.
     * This can be used to run commands, provided the player has the required permissions. Since they are being run from
     * chat, commands must be prefixed with the usual "/" slash. In signs, the command is run by the server at the
     * sign's location, with the player who used the sign as @s. Since they are run by the server, sign commands have
     * the same permission level as a command block instead of using the player's permission level, are not restricted
     * by chat length limits, and do not need to be prefixed with a "/" slash.
     */
    public static ClickEvent runCommand(String value){
        return new ClickEvent(RUN_COMMAND, value);
    }

    /**
     * Opens chat and fills in value. If a chat message was already being composed, it is overwritten.
     */
    public static ClickEvent suggestCommand(String value){
        return new ClickEvent(SUGGEST_COMMAND, value);
    }

    /**
     * Can only be used in written books. Changes to page value if that page exists.
     */
    public static ClickEvent changePage(String value){
        return new ClickEvent(CHANGE_PAGE, value);
    }

    /**
     * Copies value to the clipboard.
     */
    public static ClickEvent copyToClipboard(String value){
        return new ClickEvent(COPY_TO_CLIPBOARD, value);
    }
}
