main: ch.swisssmp.shops.ShopsPlugin
version: 4
api-version: 1.13
name: Shops
author: detig_iii
description: Konfigurierbare Villager Shops
load: startup
depend: [WebCore,WorldGuard,EventPoints,NPCs,CustomItems,CustomEditorAPI]
permissions: 
  shop.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
  shop.craft:
    default: op
    description: Erlaubt das Craften von Shops
  shop.create:
    default: op
    description: Erlaubt das Erstellen und Verwalten von Shops
commands:
  shop:
    usage: "Verwendung: /<command> <subcommand> [Argumente]"
    description: Hauptbefehl zur Verwaltung von Shops
    permission: shop.admin
  shop create:
    usage: "Verwendung: /<command> <subcommand>"
    description: Erstellt einen Shop an deiner Position
    permission: shop.admin