main: ch.swisssmp.random.RandomItemAPI
version: 1.1
api-version: 1.13
name: RandomItemAPI
author: detig_iii
description: Ermöglicht anderen Plugins Verwendung von Zufallswerten auf Items
permissions:
  random.admin:
    description: Erlaubt Verwendung des Zufall Befehls
    default: op
commands:
  randomize:
    description: Fügt Items Zufallswerte hinzu. Entfernt eine Einstellung wenn nicht alle Parameter angegeben werden oder die Einstellung keinen Zufall zulässt.
    usage: "/<command> <subcommand> [Argumente]"
    permission: random.admin
  randomize menge:
    description: Zufällige Anzahl, wird zu mehreren Stacks wenn die Anzahl grösser ist als Stack Limit und das Inventar das zulässt
    usage: "/<command> <subcommand> [Min] [Max]"
    permission: random.admin
  randomize chance:
    description: Zahl von 0.00%-100%
    usage: "/<command> <subcommand> [Wahrscheinlichkeit]"
    permission: random.admin
  randomize haltbarkeit:
    description: Beschädigung, nur ganze Zahlen (z.B. 364). Achtung grosse Zahl bedeutet grosse "Beschädigung" und nicht "Verbleibende Haltbarkeit".
    usage: "/<command> <subcommand> [Min] [Max]"
    permission: random.admin
  randomize verzauberung:
    description: 
    usage: |
      "/<command> <subcommand> [Verzauberung] [Stufe] [Wahrscheinlichkeit] §7- Verzauberung mit fester Stufe (0 um zu entfernen)"
      "/<command> <subcommand> [Verzauberung] [Min] [Max] [Wahrscheinlichkeit] §7- Verzauberung mit zufälliger Stufe"
    permission: random.admin
  randomize schaden:
    description: Angriffschaden, Komma Stellen erlaubt (z.B. 5.5)
    usage: "/<command> <subcommand> [Max]" 
    permission: random.admin
  randomize geschwindigkeit:
    description: Angriffsgeschwindigkeit, Komma Stellen erlaubt (z.B. 1.6)
    usage: "/<command> <subcommand> [Min] [Max]"
    permission: random.admin
  randomize rüstung:
    description: Nur ganze Zahlen (z.B. 2)
    usage: "/<command> <subcommand> [Min] [Max]"
    permission: random.admin
  randomize härte:
    description: Nur ganze Zahlen (z.B. 1)
    usage: "/<command> <subcommand> [Min] [Max]"
    permission: random.admin
  randomize nichts:
    description: Entfernt alle Zufallseinstellungen von diesem Stack
    usage: "/<command> <subcommand>"
    permission: random.admin