main: ch.swisssmp.tablist.TabListPlugin
version: 3
api-version: 1.13
name: TabList
author: detig_iii
description: Make the Tab List beautiful again
softdepend: [PermissionManager]
permissions:
  tablist.admin:
    description: Allows you to change settings
    default: op
commands:
  tablist:
    description: Perform various actions
    usage: /tablist [reload/debug]
    permission: tablist.admin