main: ch.swisssmp.holosign.HoloSign
version: 2
api-version: 1.13
name: HoloSign
author: detig_iii
description: Ermöglicht schwebende Texte
permissions: 
  holosign.admin:
    default: op
    description: Erlaubt Verwendung des Plugins
commands:
  sign:
    usage: "/<command> <subcommand> <Argumente>"
    description: Basisbefehl
    permission: holosign.admin
  sign create:
    usage: "/<command> <subcommand> <Farbe> <Text>"
    description: Platziert einen schwebenden Text
    permission: holosign.admin
  sign remove:
    usage: "/<command> <subcommand> <Distanz> <Text>"
    description: Entfernt schwebende Texte
    permission: holosign.admin