main: ch.swisssmp.permissionmanager.PermissionManager
version: 1.3
api-version: 1.13
name: PermissionManager
author: detig_iii
description: Erlaubt Permission Management vom Web-Interface
depend: [WebCore, TabList, SwissSMPUtils]
permissions:
  permissionmanager.admin:
    default: op
    description: Erlaubt die Verwaltung des Plugins
  permissionmanager.promote:
    default: op
    description: Erlaubt Promoten von Spielern
  permissionmanager.demote:
    default: op
    description: Erlaubt Demoten von Spielern
  permissionmanager.commands.autocomplete:
    default: op
    description: Erlaubt Auto-Vervollständigung von Befehlen
commands:
  permission:
    usage: |
      /permission check [Spieler] [Berechtigung]
      /permission debug
      /permission reload
      /permission user [Spieler]
      /permission rank [Rang]
      /permission city [Stadt]
    description: Allgemeine Funktionen
    permission: permissionmanager.admin
    aliases: [pex,perm]
  promote:
    usage: /promote [user]
    description: Lasse einen Spieler aufsteigen
    permission: permissionmanager.promote
  demote:
    usage: /demote [user]
    description: Lasse einen Spieler absteigen
    permission: permissionmanager.demote