main: ch.swisssmp.personalsaddles.PersonalSaddlesPlugin
version: 3
api-version: 1.13
name: PersonalSaddles
author: detig_iii
description: Crafte private Sattel zum Schutz deiner Pferde
depends: [SwissSMPUtils]
permissions:
  personalsaddle.craft:
    description: Erlaubt das Crafting von persönlichen Sätteln
    default: op
  personalsaddle.admin:
    description: Erlaubt Administration des Plugins
    default: op