main: ch.swisssmp.waypoints.WaypointAPI
version: 1.6
api-version: 1.13
name: WaypointAPI
author: detig_iii
description: Ermöglicht erstellen von Wegpunkten als Items für Editorfenster in andere Plugins
depend: [CustomItems]
softdepend: [CustomEditorAPI]
permissions:
  waypoints.admin:
    description: Erlaubt die Verwendung des Plugins
    default: op
commands:
  waypoint:
    description: Erstellt einen Wegpunkt
    usage: /<command> [Rot|Blau]
    permission: waypoints.admin
    permission-message: Du hast keine Berechtigung für diesen Befehl.
    aliases: [wegpunkt]