main: ch.swisssmp.editor.CustomEditorAPIPlugin
version: 3
api-version: 1.13
name: CustomEditorAPI
author: detig_iii
description: Erlaubt anderen Plugins Verwendung von standardisierten Inventar-Menüs
depend: [SwissSMPUtils,CustomItems]