main: ch.swisssmp.ceremonies.CeremoniesPlugin
version: 2
api-version: 1.13
name: Ceremonies
authors: [detig_iii,WhiteGuggi]
description: Vorlage für Zeremonien aller Art
depend: [SwissSMPUtils,CameraStudio,RawTextBuilderAPI]
permissions:
  ceremony.spectate:
    description: Erlaubt dir, Zeremonien als Zuschauer bezuwohnen
    default: true
commands:
  zuschauen:
    description: Teleportiert dich als Zuschauer zur zuletzt gestarteten Zeremonie
    usage: "Verwendung: /<command>"
    permission: ceremony.spectate
    aliases: [spectate]