main: ch.swisssmp.citymapdisplays.CityMapDisplaysPlugin
version: 4
api-version: 1.13
name: CityMapDisplays
author: detig_iii
description: Ermöglicht Echtzeit Displays von Städten aufgrund der Livemap
depend: [SwissSMPUtils,WebCore,LivemapRenderAPI,CustomPaintings,CitySystem,CustomItems,RawTextBuilderAPI,CustomEditorAPI,WorldManager]
permissions:
  citymapdisplays.admin:
    description: Erlaubt Verwaltung des Plugins
    default: op
  citymapdisplays.viewer:
    description: Erlaubt Verwendung des Plugins
    default: true
commands:
  citymapdisplays:
    description: Zeigt alle CityMapDisplays
    usage: "Verwendung: /<command>"
    permission: citymapdisplays.admin
    aliases: [citydisplays]
  citymapdisplay:
    description: Basisbefehl zur Verwaltung von Anzeigen
    usage: "Verwendung: /<command>"
    aliases: [citydisplay]
  citymapdisplay create:
    description: Erstellt eine neue Anzeige
    usage: "Verwendung: /<command> create [width] [height]"
  citymapdisplay remove:
    description: Entfernt eine Anzeige
    usage: "Verwendung: /<command> remove"
  citymapdisplay reload:
    description: Lädt Anzeigen neu
    usage: "Verwendung: /<command> reload"
  citymapdisplay show:
    description: Zeigt eine Stadt
    usage: "Verwendung: /<command> show [display-id] [city-id]"