main: ch.swisssmp.flyday.FlyDayPlugin
version: 2
api-version: 1.13
name: FlyDay
author: detig_iii
description: Vergibt an FlyDays automatisch Flug-Rechte
depend: [SwissSMPUtils,WebCore]
softdepend: [Lift]
permissions:
  flyday.admin:
    description: Erlaubt die Steuerung von FlyDay
    default: op
  flyday.bypass:
    description: Schliesst einen Spieler vom Einfluss des Plugins aus
    default: op
commands:
  FlyDay:
    description: Enable and disable the flyday
    permission: flyday.admin
    usage: |
      /flyday reload - Synchronisiert Flugrechte mit dem Web-Interface
      /flyday on [Welt,..] - Aktiviert Flugrechte in den angegebenen Welten
      /flyday off (Welt,..] - Deaktiviert Flugrechte (in den angegebenen Welten)