name: ZvieriPlausch
version: 4
api-version: '1.13'
main: ch.swisssmp.zvieriplausch.ZvieriPlauschPlugin
author: WhiteGuggi
description: Zvieri Minigame
depend: [SwissSMPUtils,CustomEditorAPI,NPCs,WaypointAPI,CustomItems,ResourcepackManager,WorldEdit,WorldGuard,WGRegionEvents,CustomRecipeAPI,CustomPaintings,RawTextBuilderAPI]
permissions:
  zvierigame.admin:
    default: op
    description: Erlaubt Steuerung des Plugins
  zvierigame.play:
    default: op
    description: Erlaubt Zvierigames zu spielen
commands:
  zvieriarena:
    usage: "/<command> <subcommand>"
    permission: zvierigame.admin
  zvieriarena create:
    usage: "/<command> <subcommand> <arenaname>"
    description: Erlaubt erstellen einer ZvieriArena
    permission: zvierigame.admin
  zvieriarenen:
    usage: "/<command>"
    description: Öffnet Übersicht über bisher erstellte Arenen
    permission: zvierigame.admin
  zvierigame:
    usage: "/zvierigame <subcommand>"
    description: Erlaubt Abbruch eines Spiels und reloaden der Config
    permission: zvierigame.admin
  zvierigame reload:
    usage: "/zvierigame reload"
    description: Erlaubt reloaden der Config
    permission: zvierigame.admin
  zvierigame cancel:
    usage: "/zvierigame cancel [Arenaname]"
    description: Erlaubt abbrechen eines Spiels
    permission: zvierigame.admin
  zvierirecipedisplay:
    usage: "/zvierirecipedisplay show [Arena-ID] [Gericht-Enum]"
    description: Erlaubt Ändern der Rezeptanzeige
    permission: zvierigame.play